[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python3 bot.py"

# Deshabilitar health checks porque no exponemos puerto HTTP
[service]
type = "worker"
